name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: vivekstha00
          color_snake: '3c1f7c'          
          color_dots: '5d34a2'          
          color_dots_empty: '281557'    
          color_dots_hidden: '1a0c35'   
          output_dots_max_count: 52     
          outputs: |
            dist/snake.svg
            dist/snake.gif
            
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: false
          force_orphan: true
